version: '3.8'

services:
  app:
    build: .
    container_name: go_db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=''
      - DB_NAME=go_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: go_db
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: go_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
